version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mysite1
      POSTGRES_USER: mysite1user
      POSTGRES_PASSWORD: mysite1pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    environment:
      - DJANGO_SETTINGS_MODULE=mysite1.settings
      - DB_HOST=db
      - DB_NAME=mysite1
      - DB_USER=mysite1user
      - DB_PASS=mysite1pass
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin

volumes:
  pgdata:
  minio_data: 